# .gitlab-ci.yml
stages:
  - test
  - build
  - deploy

unit_tests:
  stage: test
  script:
    - pytest tests/unit --cov=aurora --cov-report=xml
    - coverage report --fail-under=80

integration_tests:
  stage: test
  script:
    - docker-compose up -d test_env
    - pytest tests/integration --timeout=300

model_validation:
  stage: test
  script:
    - python scripts/validate_model.py --checkpoint latest
    - python scripts/check_latency.py --target 100ms
