repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: local
    hooks:
      - id: validate-configs
        name: Validate configs (strict)
        entry: python tools/validate_config.py --strict configs/*.yaml
        language: system
        pass_filenames: false
      - id: validate-events
        name: Validate AURORA events schema (last 200 lines)
        entry: python tools/validate_events.py --file logs/events.jsonl --schema observability/schema.json --last 200
        language: system
        pass_filenames: false
      - id: yamllint-configs
        name: Yamllint configs/
        entry: yamllint configs/
        language: system
        pass_filenames: false