
version: '3.8'

services:
  api:
    build: .
    container_name: aurora-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    volumes:
  - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  # Mount alerting / recording rules
  - ./ops:/etc/prometheus/rules:ro
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:9.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage:
