
[calibration]
method = "isotonic"
prequential_window = 5000
profile = "platt"

[execution]

[execution.exchange]

[execution.exchange.binance]
api_key = ""
burst = 16
enabled = false
filters_ttl_sec = 3600
mode = "paper"
recv_window_ms = 5000
rps = 8
time_sync_sec = 60

[execution.exchange.gate]
burst = 16
enabled = false
filters_ttl_sec = 3600
mode = "paper"
rps = 8
time_sync_sec = 60

[execution.fees]
default_maker_bps = 1.0
default_rebate_bps = 0.0
default_taker_bps = 7.5

[execution.router]
horizon_ms = 1000
ioc_cleanup = true
maker_offset_bps = 1.0
max_requotes_per_min = 20
mode = "hybrid"
mode_default = "hybrid"
p_min_fill = 0.5
post_only = true
spread_limit_bps = 80
t_min_requote_ms = 150
taker_escalation_ttl_ms = 1000
tca_gate = true

[execution.router.child_split]
max_children = 5
min_lot = 0.001

[execution.router.vol_spike_guard]
atr_mult = 2.0
window_s = 300

[execution.sla]
edge_floor_bps = 0.0
kappa_bps_per_ms = 0.05
max_latency_ms = 50
target_fill_prob = 0.6

[features]
profile = "minimal"

[features.scaling]
method = "robust"

[governance]

[governance.alpha_ledger]
enabled = true

[hotreload]
whitelist = ['risk.cvar.limit', 'execution.sla.max_latency_ms', 'features.scaling', 'reward.scale_in.enabled', 'execution.router.mode_default', 'execution.router.spread_limit_bps', 'tca.adverse_window_s']

[leadlag]
enable = false
lag_grid = [1, 2]

[order_sink]
mode = "sim_local"

[order_sink.sim_local]
latency_mean_ms = 50
latency_std_ms = 10
slip_bps_mean = 1.0
slip_bps_std = 0.5

[profile]

[profile.local_high]
calibration = "full"
execution_sla_max_latency_ms = 25
features = "full"
leadlag_enable = true
leadlag_lag_grid = [1, 2, 3, 5]
replay_chunk_minutes = 60
sizing_leverage = 5
sizing_max_position_usd = 20000
tca = "full"
universe_spread_bps_limit = 20
universe_top_n = 20
xai_level = "WARN"
xai_sample_every = 1
xai_sig = true

[profile.local_low]
calibration = "platt"
execution_sla_max_latency_ms = 50
features = "minimal"
leadlag_enable = false
leadlag_lag_grid = [1, 2]
replay_chunk_minutes = 30
sizing_leverage = 1
sizing_max_position_usd = 1000
tca = "surrogate"
universe_spread_bps_limit = 50
universe_top_n = 5
xai_level = "INFO"
xai_sample_every = 10
xai_sig = true

[profile.local_mid]
calibration = "platt_temp"
execution_sla_max_latency_ms = 35
features = "standard"
leadlag_enable = true
leadlag_lag_grid = [1, 2, 3]
replay_chunk_minutes = 60
sizing_leverage = 2
sizing_max_position_usd = 5000
tca = "light"
universe_spread_bps_limit = 30
universe_top_n = 10
xai_level = "INFO"
xai_sample_every = 5
xai_sig = true

[regime]

[regime.manager]
grind_quantile = 0.4
trend_quantile = 0.6

[replay]
chunk_minutes = 30

[reward]
be_buffer_bps = 2.0
be_rr = 1.0
no_progress_eps_bps = 5.0
stuck_dt_s = 300
tp_levels_bps = [20, 40, 70]
tp_sizes = [0.25, 0.35, 0.4]
trail_atr_k = 0.8
ttl_minutes = 120

[reward.scale_in]
cooldown_s = 60
enabled = true
hysteresis = 0.1
max_add_per_step = 0.2
rho = 0.5

[risk]

[risk.cvar]
alpha = 0.95
confidence = 0.975
limit = 0.02
lookback = 5000
method = "pot-gpd"

[risk.evt_pot]
bootstrap = 500
u_percentile = 0.95

[risk.limits]
cvar_usd = 150.0
dd_day_bps = 300.0
evt_max_loss_usd = 400.0
evt_quantile = 0.999
order_max_usd = 5000.0
order_min_usd = 10.0
position_usd = 25000.0

[shadow]
threshold = 0.55
topk = 16

[signal]

[signal.score]
gamma = 0.0
use_cross_asset = true

[sizing]
leverage = 1
max_position_usd = 1000

[sizing.dd_haircut]
beta = 2.0
dd_max_bps = 300.0
enabled = true

[sizing.kelly]
clip_max = 0.2
clip_min = 0.0
fraction_cap = 0.2
risk_aversion = 0.2
rr_default = 1.0

[sizing.limits]
initial_margin_pct = 0.1
leverage_max = 5.0
maintenance_margin_pct = 0.05
max_notional_usd = 5000.0
min_notional_usd = 10.0

[sizing.portfolio]
cvar_alpha = 0.975
cvar_limit = 0.08
gross_cap = 2.0
max_weight = 0.2
method = "lw_shrinkage"

[sizing.stability]
bucket_sizes = [0.0, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1.0]
hysteresis_flip_threshold = 0.2
hysteresis_threshold = 0.1
min_resize_interval_sec = 10.0

[tca]
adverse_window_s = 1
aggregate_interval_s = 300
mark_ref = "micro"
profile = "surrogate"

[tca.edge_budget]
enabled = true

[universe]
spread_bps_limit = 50
top_n = 5

[universe.ranking]
add_thresh = 0.6
drop_thresh = 0.4
ema_alpha = 0.2
min_dwell = 200
wL = 0.35
wP = 0.25
wR = 0.15
wS = 0.25

[xai]
level = "INFO"
sample_every = 10
sig = true

[xai.decision_log]
enabled = true
