# tmp config with empty critical sections to trigger null/empty check
market_data = { source = "testnet_binance" }

[order_sink]
mode = "sim_local"

[orders]
enabled = false

[execution]
sla = { max_latency_ms = 25 }

# critical sections present but empty
risk = {}
sizing = {}
reward = {}
tca = {}
xai = {}
universe = {}
