thresholds:
  max_dro_penalty: null
  max_churn_per_1k: null
  dcts_min: null
meta:
  generated: '2025-08-19T18:41:36.823771Z'
  alpha_target: 0.1
  samples: 1
  percentiles_source:
    dro_penalty_p95: .nan
    churn_p95: .nan
    dcts_p10: .nan
    coverage_delta_p95: .nan
