symbol: "BTC/USDT"
timeframe: "1s"
dry_run: true
testnet: true
use_futures: true

# Exchange connection (Binance)
exchange:
  id: binanceusdm          # binanceusdm for USDT-M futures, binance for spot
  use_futures: true        # true -> futures (USDM), false -> spot
  testnet: true            # true -> sandbox/testnet
  symbol: "BTC/USDT"       # trading symbol
  leverage: 50             # optional, best-effort for futures
  # Credentials come from environment variables (do not hardcode keys!)
  api_key_env: BINANCE_API_KEY
  api_secret_env: BINANCE_API_SECRET
  # HTTP/CCXT options
  recv_window_ms: 5000
  timeout_ms: 20000
  adjust_for_time_diff: true

alpha:
  obi_levels: 5
  tfi_window: 50
  micro_weight: 1.0
  obi_weight: 1.0
  tfi_weight: 1.0
  entry_threshold: 0.35
  exit_threshold: 0.05
  # Reconfirmation policy for entries:
  # - both: require current score AND average over window to pass (legacy default)
  # - any: allow if either passes (testnet-friendly)
  # - avg: require only average over window
  # - now: require only current score
  reconfirm: any
  reconfirm_window_ticks: 2

risk:
  max_inventory: 0.01
  max_drawdown_pct: 2.0
  vol_window: 120
  vol_max: 0.006
  take_profit_ticks: 2.0
  stop_loss_ticks: 2.0

execution:
  maker_mode: true
  post_only: true
  order_size: 0.001
  cancel_after_s: 5
  fees_bps: 1.0
  trades_per_minute_limit: 10
  max_symbol_exposure_usdt: 1000
  spread_guard_bps_max: 8

leverage: 50

aurora:
  enabled: true
  base_url: http://127.0.0.1:8000
  mode: shadow

# 15m clock-gate windows (seconds within 15m bar)
clock_gate:
  enabled: false
  windows_sec:
    - [20, 90]    # ORB 0:20–1:30
    - [420, 510]  # Mid-bar 7:00–8:30
    - [840, 870]  # Late 14:00–14:30
