# Adaptive ICP configuration with dynamic alpha modulation (AUR-ALPHA-710)
alpha_target: 0.10
eta: 0.01
window: 1000
quantile_fallback: p2
# Dynamic alpha modulation parameters
alpha_min: 0.06        # floor when volatility low (defaults ~0.6*alpha_target if omitted)
alpha_max: 0.20        # cap under sustained instability (defaults 2x base capped at 0.5)
aci_beta: 0.20         # smoothing factor for ACI EMA
aci_up_thresh: 1.25    # threshold above which we start widening (ACI>1 means elevated instability)
alpha_k_up: 0.50       # proportional gain for widening
cooldown_steps: 500    # steps to hold widened alpha before decay attempts
decay_tau: 300         # exponential relaxation time constant back to base
