# Aurora — default configuration (SSOT)
# NOTE: Sensitive secrets (API keys) must be provided via ENV overrides, e.g.:
#   export AURORA__EXECUTION__EXCHANGE__BINANCE__API_KEY="..."
# Runtime tuning is restricted by hotreload.whitelist (see bottom).

[risk.limits]
# Hard pre-trade risk guards (any breach = DENY)
dd_day_bps = 300.0           # daily drawdown cap
position_usd = 25000.0       # |net position| cap
order_min_usd = 10.0         # minimum order notional
order_max_usd = 5000.0       # maximum order notional
cvar_usd = 150.0             # CVaR limit per trade
evt_quantile = 0.999         # EVT tail quantile
evt_max_loss_usd = 400.0     # EVT max loss threshold

[risk.evt_pot]
# EVT Peaks-Over-Threshold parameters
u_percentile = 0.95          # threshold percentile for POT
bootstrap = 500              # bootstrap samples for CI

[risk.cvar]
# Tail risk guardrail for sizing/governance
limit = 0.02                # portfolio CVaR cap (post-TCA), fraction of equity
alpha = 0.95                # CVaR confidence level
method = "pot-gpd"          # {'historical','gaussian','cornish-fisher','student-t','pot-gpd'}
confidence = 0.975          # POT tail-fit confidence for diagnostics
lookback = 5000             # observations for risk window

[execution.sla]
# Latency gate and target fill probability for TCA router
max_latency_ms = 25
kappa_bps_per_ms = 0.05
target_fill_prob = 0.6
edge_floor_bps = 0.0

[execution.router]
horizon_ms = 1000
p_min_fill = 0.5
mode = "hybrid"             # {'maker','taker','hybrid'}
tca_gate = true

[execution.exchange.binance]
# Do not commit keys here; use ENV overrides as noted above.
enabled = false
api_key = ""
mode = "paper"
recv_window_ms = 5000
time_sync_sec = 60
filters_ttl_sec = 3600
rps = 8
burst = 16

[execution.exchange.gate]
enabled = false
mode = "paper"
time_sync_sec = 60
filters_ttl_sec = 3600
rps = 8
burst = 16

[execution.fees]
# Default exchange fees (when exchange doesn't provide)
default_maker_bps = 1.0
default_taker_bps = 7.5
default_rebate_bps = 0.0

[features.scaling]
# Feature scaling used across OBI/microprice/TFI pipelines
method = "robust"           # {'standard','robust','minmax','none'}

[signal.score]
# S = w^T x + gamma * beta_{i|SOL} * r_SOL(t - tau*)
gamma = 0.0
use_cross_asset = true

[calibration]
# Probability calibration for scores (prequential)
method = "isotonic"         # {'platt','isotonic','none'}
prequential_window = 5000

[regime.manager]
# Tradeable regimes and quantile gates
trend_quantile = 0.6
grind_quantile = 0.4

[tca.edge_budget]
# Enable TCA-aware entry gate
enabled = true

[sizing.kelly]
# Kelly sizing parameters (production-safe defaults)
risk_aversion = 0.2         # Conservative: 0.15-0.25 for anti-overbetting
clip_min = 0.0
clip_max = 0.2
rr_default = 1.0
fraction_cap = 0.2

[sizing.portfolio]
# Portfolio optimization parameters (production-safe defaults)
method = "lw_shrinkage"
gross_cap = 2.0             # 2x equity max exposure
max_weight = 0.2            # Max 20% per asset
cvar_alpha = 0.975
cvar_limit = 0.08           # 0.8x DD_max for conservative sizing

[sizing.dd_haircut]
# DD haircut parameters
dd_max_bps = 300.0          # Match risk.limits.dd_day_bps
beta = 2.0                  # Haircut steepness
enabled = true

[sizing.stability]
# Stability controls for production
hysteresis_threshold = 0.1      # τ = 0.1 * current_f
hysteresis_flip_threshold = 0.2 # τ_flip = 0.2 * current_f
min_resize_interval_sec = 10.0  # Conservative: 5-10s between resizes
bucket_sizes = [0.0, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1.0]  # Discrete sizes

[sizing.limits]
# Order sizing limits (production-safe)
min_notional_usd = 10.0
max_notional_usd = 5000.0
leverage_max = 5.0           # Max leverage for futures
initial_margin_pct = 0.1     # 10% initial margin
maintenance_margin_pct = 0.05 # 5% maintenance margin

[governance.alpha_ledger]
# Alpha governance ledger
enabled = true

[xai.decision_log]
# DecisionLog for traceability (pairs with config_hash and schema_version)
enabled = true

[hotreload]
# Only these keys (or their descendants) are allowed to change at runtime.
whitelist = [
  "risk.cvar.limit",
  "execution.sla.max_latency_ms",
  "features.scaling",
  "reward.scale_in.enabled",
  "execution.router.mode_default",
  "execution.router.spread_limit_bps",
  "tca.adverse_window_s"
]

[universe.ranking]
# Universe ranking weights and hysteresis parameters
wL = 0.35                  # liquidity weight
wS = 0.25                  # spread weight  
wP = 0.25                  # fill probability weight
wR = 0.15                  # regime weight
add_thresh = 0.60          # hysteresis add threshold
drop_thresh = 0.40         # hysteresis drop threshold
min_dwell = 200            # minimum dwell ticks
ema_alpha = 0.2            # EMA smoothing alpha

[shadow]
# Shadow runner configuration
threshold = 0.55           # decision threshold for enter/deny
topk = 16                  # top-K symbols to rank

[reward]
# Reward management parameters (TP ladder, trail-stop, breakeven, anti-martingale)
tp_levels_bps = [20, 40, 70]    # TP ladder levels in bps
tp_sizes = [0.25, 0.35, 0.40]  # TP exit sizes (sum <= 1.0)
trail_atr_k = 0.8              # Trail distance multiplier (ATR)
be_rr = 1.0                    # Breakeven activation R/R ratio
be_buffer_bps = 2.0             # Breakeven buffer in bps
ttl_minutes = 120               # Position time-to-live in minutes
stuck_dt_s = 300                # No-progress timeout in seconds
no_progress_eps_bps = 5.0       # No-progress epsilon in bps

[reward.scale_in]
# Anti-martingale scale-in parameters
enabled = true
hysteresis = 0.1               # Hysteresis threshold for scale-in
rho = 0.5                      # Scale-in throttle factor
max_add_per_step = 0.2         # Max additional fraction per step
cooldown_s = 60                # Cooldown between scale-in attempts

[execution.router]
# Enhanced execution router parameters
mode_default = "hybrid"         # Default routing mode
maker_offset_bps = 1.0          # Maker offset from best bid/ask
taker_escalation_ttl_ms = 1000  # Taker escalation timeout
t_min_requote_ms = 150          # Min time between re-quotes
max_requotes_per_min = 20       # Max re-quotes per minute
post_only = true                # Use post-only for maker orders
ioc_cleanup = true              # Use IOC for cleanup orders
spread_limit_bps = 80           # Max spread for queue-aware re-peg

[execution.router.child_split]
# Child order splitting parameters
min_lot = 0.001                 # Minimum child lot size
max_children = 5                # Maximum number of child orders

[execution.router.vol_spike_guard]
# Volatility spike guard parameters
atr_mult = 2.0                  # ATR multiplier for spike detection
window_s = 300                  # Volatility window in seconds

[tca]
# Transaction Cost Analysis parameters
adverse_window_s = 1            # Adverse selection window in seconds
mark_ref = "micro"              # Price reference for TCA (mid/micro)
aggregate_interval_s = 300      # Aggregation interval for TCA metrics
