r1:
  improvement_eps_reporting: 5e-4
  tau_drift_limit: 0.05
  tau_drift_ema_halflife_s: 3600
  selector_top_k: 5
  score_weights:
    alpha_dEfe: 1.0
    beta_dEmp: 0.5
    gamma_dHomeo: 0.5
    lambda_acf: 0.2
    lambda_spec: 0.2
    lambda_energy: 0.1
    lambda_latency: 0.1
