exchange:
  id: ${EXCHANGE_ID:binanceusdm}
  testnet: ${EXCHANGE_TESTNET:true}
  use_futures: ${EXCHANGE_USE_FUTURES:true}
  recv_window_ms: ${BINANCE_RECV_WINDOW:20000}
dry_run: ${DRY_RUN:true}
aurora_mode: ${AURORA_MODE:shadow}
rate_limit: true
ccxt_options:
  defaultType: future
  adjustForTimeDifference: true
  warnOnFetchOpenOrdersWithoutSymbol: false
