# tmp config missing execution.sla_max_latency_ms
market_data = { source = "testnet_binance" }

[order_sink]
mode = "sim_local"

[orders]
enabled = false

[execution]
# sla_max_latency_ms intentionally omitted
