# tmp config: live source with non-sim_local sink to trigger invariant
market_data = { source = "live_binance" }

[order_sink]
mode = "net"

[orders]
enabled = true

[execution]
sla_max_latency_ms = 25
