groups:
  - name: aurora_acceptance
    rules:
      - alert: AuroraHighLatencyP95
        expr: histogram_quantile(0.95, sum by (le,profile) (rate(aurora_acceptance_latency_ms_bucket[5m]))) > 120
        for: 10m
        labels: {severity: warning}
        annotations: {summary: "Latency p95 above SLO for {{$labels.profile}}"}

      - alert: AuroraCoverageBelowTarget
        expr: aurora_icp_coverage_ema{profile=~".+"} < 0.90
        for: 15m
        labels: {severity: critical}
        annotations: {summary: "Coverage EMA below target for {{$labels.profile}}"}

      - alert: AuroraHighSurprisalP95
        expr: histogram_quantile(0.95, sum by (le,profile) (rate(aurora_acceptance_surprisal_v2_bucket[15m]))) > 2.5
        for: 10m
        labels: {severity: warning}
        annotations: {summary: "Surprisal p95 above guard for {{$labels.profile}}"}

      - alert: AuroraProlongedBlockState
        expr: aurora_acceptance_state{state="BLOCK"} == 1
        for: 15m
        labels: {severity: warning}
        annotations: {summary: "FSM stuck in BLOCK for {{$labels.profile}}"}

      - alert: AuroraRapidStateFlapping
        expr: sum by (profile) (rate(aurora_acceptance_state_transitions_total[10m])) > 6
        for: 10m
        labels: {severity: info}
        annotations: {summary: "High FSM transition rate for {{$labels.profile}}"}

  - name: aurora_summary_gate
    rules:
      - alert: SummaryGateFail
        expr: aurora_summary_gate_last_status{branch=~"main|release/.*"} == 1
        for: 5m
        labels: {severity: critical}
        annotations: {summary: "Summary Gate FAIL on protected branch {{$labels.branch}} (sha {{$labels.sha}})"}

      - alert: FrequentGateFail
        expr: increase(aurora_summary_gate_fail_total[24h]) > 3
        for: 0m
        labels: {severity: warning}
        annotations: {summary: "Summary Gate FAIL frequency > 3 in last 24h"}
