# Aurora testnet profile (safe defaults)
# Tailored for testnet/shadow runs: conservative risk, permissive observability, reasonable guards.

env: testnet
api:
  host: 127.0.0.1
  port: 8000

security:
  # Override via OPS_TOKEN/AURORA_OPS_TOKEN if needed
  ops_token: "change-me-testnet-ops-token-XXXXXXXXXXXXXXXX"

aurora:
  latency_guard_ms: 40
  latency_window_sec: 60
  cooloff_base_sec: 120
  halt_threshold_repeats: 2

guards:
  spread_bps_limit: 100
  latency_ms_limit: 400
  vol_guard_std_bps: 300
  trap_guard_enabled: true

risk:
  pi_min_bps: 2.0
  dd_day_pct: 10.0
  max_concurrent: 2
  size_scale: 0.1

slippage:
  eta_fraction_of_b: 0.25

trap:
  window_s: 2.0
  levels: 5
  z_threshold: 1.64
  cancel_pctl: 90
  score_threshold: 0.8

sprt:
  enabled: true
  alpha: 0.05
  beta: 0.10
  sigma: 1.0
  max_obs: 10

observability:
  ack:
    ttl_s: 300
    scan_period_s: 1.0
