# Aurora testnet override example. Overlay on top of aurora/base.yaml
# Usage: set AURORA_CONFIG=AURORA/testnet.example or copy as testnet.yaml and select via AURORA_CONFIG_NAME.

env: testnet

aurora:
  latency_guard_ms: 50

risk:
  pi_min_bps: 1.0
  max_concurrent: 2
  size_scale: 0.2

guards:
  spread_bps_limit: 120
  latency_ms_limit: 500
  trap_guard_enabled: true

slippage:
  eta_fraction_of_b: 0.25

observability:
  ack:
    ttl_s: 180
    scan_period_s: 1.0
