name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint (ruff)
        run: |
          pip install ruff
          ruff check .
      - name: Validate configs (strict for PR)
        if: github.event_name == 'pull_request'
        run: |
          python tools/validate_config.py --strict configs/*.yaml || (echo "Config validation failed" && exit 1)
      - name: Validate configs (strict + fail-unknown on main)
        if: github.event_name == 'push'
        run: |
          python tools/validate_config.py --strict --fail-unknown configs/*.yaml || (echo "Config validation failed" && exit 1)
      - name: Run unit tests with coverage
        run: |
          pytest --cov=. --cov-report=term --cov-report=xml --maxfail=1 -q
      - name: Run integration tests
        run: |
          pytest tests/integration/ -v --tb=short
      - name: Run E2E tests
        run: |
          pytest tests/e2e/ -v --tb=short
      - name: Run order lifecycle tests
        run: |
          pytest tests/integration/oms/test_order_lifecycle.py -v
      - name: Run concurrent order tests
        run: |
          pytest tests/integration/oms/test_concurrent_orders.py -v
      - name: Run trade flow simulator tests
        run: |
          pytest tests/e2e/test_trade_flow_simulator.py -v
      - name: Enforce coverage >=90%
        run: |
          coverage xml
          python - << 'PY'
          import xml.etree.ElementTree as ET, sys
          tree = ET.parse('coverage.xml')
          rate = float(tree.getroot().attrib['line-rate']) * 100
          print(f"Coverage: {rate:.2f}%")
          if rate < 90:
              print('Coverage threshold not met (90%)')
              sys.exit(1)
          PY
  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t aurora-api:ci .
