name: perf-nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  perf:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements*.txt') }}
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt -r requirements-dev.txt
      - name: Run perf tests (p95)
        run: |
          set -o pipefail
          pytest -q tests/perf/test_pretrade_perf.py -m "not skip" --maxfail=1 2>&1 | tee perf-report.txt
      - name: Build canary summary
        run: |
          python tools/canary_summary.py \
            --events logs/events.jsonl \
            --out-ts reports/latency_p95_timeseries.csv \
            --out-flow reports/escalations_flow.md \
            --out-md reports/canary_60min_summary.md || true
      - name: Enforce summary gate (strict)
        if: ${{ hashFiles('logs/events.jsonl') != '' }}
        run: |
          python tools/summary_gate.py --summary reports/canary_60min_summary.md --events logs/events.jsonl --strict --status-out reports/summary_gate_status.json
      - name: Publish gate status
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: summary_gate_status
          path: reports/summary_gate_status.json
          if-no-files-found: ignore
      - name: Tail last RISK/HEALTH events (on failure)
        if: failure() && hashFiles('logs/events.jsonl') != ''
        run: |
          echo "Last 10 RISK/HEALTH events:" && \
          tail -n 200 logs/events.jsonl | egrep '"type":"(RISK|HEALTH)\.' | tail -n 10 || true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nightly-artifacts
          path: |
            perf-report.txt
            reports/latency_p95_timeseries.csv
            reports/escalations_flow.md
            reports/canary_60min_summary.md
          if-no-files-found: ignore
